eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-7f8a7eeb-9f08-4546-90a8-2c4d9933a8de.apps.cumuluslabs.io/
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 6
security:
  basic:
    enabled: false
